# Generated by Django 4.1.4 on 2023-01-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_wallet_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='accounts.account'),
        ),
    ]
